# Generated by Django 2.1.7 on 2019-03-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wordsEntry',
            new_name='wordEntry',
        ),
        migrations.RenameField(
            model_name='wordentry',
            old_name='words',
            new_name='word',
        ),
    ]
