# Generated by Django 2.1.7 on 2019-03-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20190330_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordentry',
            old_name='gondiSynonyms',
            new_name='gondiFile',
        ),
    ]
