# Generated by Django 2.1.7 on 2019-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20190330_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordentry',
            name='pId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
