# Generated by Django 2.1.7 on 2019-03-30 11:07

from django.db import migrations, models
import mainpage.custom.PointFileStorage


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_wordentry_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordentry',
            name='gondiFile',
            field=models.FileField(null=True, storage=mainpage.custom.PointFileStorage.PointFileStorage(), upload_to=''),
        ),
    ]
