# Generated by Django 2.1.7 on 2019-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20190330_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordentry',
            name='gondiFile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
